# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c9fac7a8573fb617002715e6fc77eaeb92aeb3bfb5b92630d0c93f5d219dd00419564bfe9b04f1387b8dded005b6afa7b75340d4e731e451a1f486c1461fab5

test:
  secret_key_base: 0bc65506dd7bb26e38ff295d40356becf174177c5b55a394222cd132a89409b2abd5ff08bc1bde583d9b6c94956ff2b34ef1d12854c6df20b6fb569d67b23dd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
